### ISSUE TITLE
Platform.sh Migration Plan

### ISSUE THREAD

**Issue by mcneely** [joindin/joindin-platformsh#1]
1. Announce on blog, wait one week.
2. Place Maintenance Screen on Web2 (Combell)
3. Place Following Code top of API Front Controller (combell):
```
header('HTTP/1.1 503 Service Temporarily Unavailable');
header('Status: 503 Service Temporarily Unavailable');
header('Retry-After: 300');
die();
```
4. Disable Legacy
5. Copy Image folder over.
6. Migrate Database
7. Change platform to joind.in domain
8. Change platform config to point to proper url for images.
9. Point API cname to platform and wait for propagation
10. Point main cname to platform.
11. Wipe sweat off brow.

**Comment by liam-wiltshire** [comment]
Just as a note, as part of this https://legacy.joind.in would need to come offline or be on a holding page, as that can also alter the db.

**Comment by mcneely** [comment]
Noted.

**Comment by heiglandreas** [comment]
To speed up the propagation we perhaps should *now*  set the TTL for api.joind.in and joind.in to a reasonable low value like 300 or even less...

**Comment by mcneely** [comment]
Probably not going to matter as api and web are all under cloudflare and the ip's shouldn't change. Propagation is only how fast it takes cloudflare to update, not the rest of the web.

**Comment by iansltx** [comment]
We're live!
