### ISSUE TITLE
Make platform.sh repo a clone of github

### ISSUE THREAD

**Issue by heiglandreas** [joindin/joindin-platformsh#2]
Using the `platform`-CLI we can actually create an integration for platform.sh meaning that the platform.sh-Repo will be a clone from the github-repo that will be updated everytime a merge to master is pushed to github.

That would save us from having to do the pushes manually. Every time the platformsh-repo on github receives a merge it would automatically trigger an update of the platform.sh-repo. Which would in turn build the new deployment.

The drawback is that the integration needs the API-Key from someone with access to the repo. So IMO we should create a "bot"-user that would then be used to create the OAuth-Token for the lpatform-Integration.

The appropriate command is `platform integration:add` which will then ask some questions where the defaults should be sensible enough....

**Comment by mcneely** [comment]
This was done this morning.
