### ISSUE TITLE
Cache files/images for the duration we did at Combell

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-platformsh#3]
The old Apache cache conf was as follows:

```
    ExpiresActive On
    ExpiresDefault A0
    <FilesMatch "\.(ico|flv|pdf|mov|mp3|wmv|ppt)$">
        ExpiresDefault A300
        Header append Cache-Control "public"
    </FilesMatch>

    <FilesMatch "\.(gif|jpg|jpeg|png|swf|txt|js|css)$">
        ExpiresDefault A3600
        Header append Cache-Control "public"
    </FilesMatch>
```

We'll need something else for platform.sh:

https://docs.platform.sh/configuration/routes/cache.html#http-cache

If we set headers correctly, Cloudflare will cache this stuff for us, and we'll get a nice boost in page load speed as a bunch of our traffic will be served from their edge rather than Platform.sh.

EDIT: Looks like this is what we're looking for: https://docs.platform.sh/configuration/app/web.html#locations

**Comment by mcneely** [comment]
I got this.

**Comment by iansltx** [comment]
Not fixed. If you request e.g. https://joind.in/inc/img/event_icons/icon-7174-small.png you'll get back a no-cache header, and an Expires header of right now.

**Comment by mcneely** [comment]
Should be working now.
